### ISSUE TITLE
Babel 7 support

### ISSUE THREAD

**Issue by adambedford** [ember-cli/ember-cli-htmlbars-inline-precompile#105]
Will this addon support Babel 7 soon?
I'm running into an issue over [here](https://github.com/ember-cli/ember-cli/issues/7004) that I hope will be fixed by Babel 7, but I haven't been able to get that working with `ember-cli-htmlbars-inline-precompile`

**Comment by alexlafroscia** [comment]
With `ember-cli-babel@7` released, it would be really nice to clarify the compatibility story here!

**Comment by alexlafroscia** [comment]
Sweet! I'm can try to put that PR together since I'm trying to get our application at work using the latest Babel

**Comment by wagenet** [comment]
See #110
