### ISSUE TITLE
the plugin didn't export a Plugin instance

### ISSUE THREAD

**Issue by congwenma** [ember-cli/ember-cli-htmlbars-inline-precompile#108]
I am running into this problem when running ember scripts

`The plugin {"_parallelBabel":{"requireFile":"./node_modules/ember-cli-htmlbars-inline-precompile/lib/require-from-worker","buildUsing":"build","params":{"templateCompilerPath":"./bower_components/ember/ember-template-compiler","parallelConfig":[]}}} didn't export a Plugin instance`

What is the problem ember-cli is running into here? What would be a good strategy for debugging these type of problems?

I am running:
ember version 1.13.13
node 10

**Comment by rwjblue** [comment]
sorry I missed this, closing for now (archiving the repo)
