### ISSUE TITLE
Does not respect `ember-cli-htmlbars`' `wrapper.cacheKey()`

### ISSUE THREAD

**Issue by amiller-gh** [ember-cli/ember-cli-htmlbars-inline-precompile#109]
### Expected Behavior:
Both `ember-cli-htmlbars` and `ember-cli-htmlbars-inline-precompile` should allow plugins to provide the same caching scheme.

### Observed Behavior: 
`ember-cli-htmlbars` allows plugins to provide a custom cache key if the addon's `baseDir()` is not sufficient: https://github.com/ember-cli/ember-cli-htmlbars/blob/master/ember-addon-main.js#L121

`ember-cli-htmlbars-inline-precompile` does not allow for this: https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L117

### Proposed Fix:
Port `ember-cli-htmlbars`' plugin `cacheKey()` method to `ember-cli-htmlbars-inline-precompile`.

**Comment by rwjblue** [comment]
This should be resolved now (see https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/issues/298, but this library is being deprecated completely in favor of "just using ember-cli-htmlbars").
