### ISSUE TITLE
use Ember.HTMLBars.compile("…") within your tests

### ISSUE THREAD

**Issue by allthesignals** [ember-cli/ember-cli-htmlbars-inline-precompile#242]
> If you need stuff like this, you need to include ember-template-compiler.js in your test-build and use Ember.HTMLBars.compile("…") within your tests.

The docs mention this. How do I do that?

**Comment by rwjblue** [comment]
In general it's best to _not_ do that, can you help me understand how/why you need dynamic templates?

---

I believe you should do:

```js
// ember-cli-build.js
module.exports = function(defaults) {
  let { project } = defaults;
  let app = new EmberApp(defaults, {

  });
  
  let ember = project.findAddonByName('ember-source');

  app.import(ember.paths.templateCompiler, {
    // if you only want for tests, you would add this
    // type: 'test'
  });

  return app.toTree();
};
```

**Comment by allthesignals** [comment]
@rwjblue thanks for the response! I'll give that a try...

> In general it's best to _not_ do that, can you help me understand how/why you need dynamic templates?

I realize it's sort of awkward, but I ran into this because I was working on some component test stubs that had partially-shared template code. In this case I was trying to "extend" what the template of one component stub was _yielding_ (in an effort to prevent duplication). 

For example,

```
export const someTemplateToDynamicallyCompile = `
  {{yield (hash thing=prop)}}
`;
```

```
const anotherTemplate = `
  ${someTemplateToDynamicallyCompile}
    {{something-else-to-add}}
`
```

A yielded hash imo is like a public interface for a component block which is why I might want to programmatically "extend" it in some cases. But, the difficulty here is probably a signal from my app that I need to refactor something.
