### ISSUE TITLE
Move functionality to ember-cli-htmlbars and deprecate?

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-htmlbars-inline-precompile#298]
The majority of the code in this addon is actually **copied** from ember-cli-htmlbars. It doesn't seem obviously better to force users to understand the difference between ember-cli-htmlbars and ember-cli-htmlbars-inline-precompile.

I think we should add functionality to ember-cli-htmlbars to setup the `babel-plugin-htmlbars-inline-precompile` itself (btw, that being its own package seems totally fine to me since its fundamentally different as a babel plugin), and deprecate this package.

This will reduce the overall mental overhead of our users (they don't need to track the difference between these two similarly named libraries), and reduces overall technical complexity. Seems win / win to me...

Any objections?

**Comment by rwjblue** [comment]
Chatted a bit with @stefanpenner about this, going to start moving forward...

**Comment by Turbo87** [comment]
SGTM! 👍

**Comment by kellyselden** [comment]
Is there any benefit lost from the dep vs devDep separation you might get, like from an addon perspective?

**Comment by rwjblue** [comment]
> Is there any benefit lost from the dep vs devDep separation you might get, like from an addon perspective?

No, I don't think so. ember-cli-htmlbars behaves basically in the same way as this package (when a dep of an addon it only processes that addon's templates). The only difference would be that you can't have _just_ ember-cli-htmlbars-inline-precompile support (vs having support for both template files and inline ones).
