### ISSUE TITLE
ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`

### ISSUE THREAD

**Issue by rinoldsimon** [ember-cli/ember-cli-htmlbars-inline-precompile#38]
Deprecation message while starting Ember serve !.

> ember-cli-htmlbars-inline-precompile is opting out of caching due to an AST plugin that does not provide a caching strategy: `v-get`

preprocessors are supposed to provide a caching mechanism now, but perhaps those modules don't do it yet

**Comment by simonihmig** [comment]
After upgrading an addon to ember-cli 2.7.0 I get similar messages, see the TravisCI log here: https://travis-ci.org/kaliber5/ember-bootstrap/builds/152026260

**Comment by rwjblue** [comment]
This is the same underlying issue as https://github.com/ember-cli/ember-cli-htmlbars/issues/91, and the error is with the individual AST plugins. 

In this case, it is provided by ember-cp-validations which was fixed in https://github.com/offirgolan/ember-cp-validations/pull/305.
