### ISSUE TITLE
templateCompiler change during session does not invalidate the cache

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/ember-cli-htmlbars-inline-precompile#41]
https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/pull/34#discussion_r75365453

this results in a rebuild being required, instead we should be sure to set this up so the cache-key is  recalculated on each rebuild.

**Comment by rwjblue** [comment]
While we can definitely fix this, it seems unlikely that we should. Now that ember itself is provided by `npm` via `ember-source` (and `package.json` changes require a server restart), detecting and updating the `ember-template-compiler.js` change would actually end up with a mismatch between the `ember.debug.js` in use and the template compiler being used for inline precompilation.

I'm going to close this for now (please reopen if you disagree)...
