### ISSUE TITLE
How to render outside of tests?

### ISSUE THREAD

**Issue by rwwagner90** [ember-cli/ember-cli-htmlbars-inline-precompile#44]
I've been trying to use this to render template strings into markup that I can drop into 3rd party libraries and such, but have had no luck. There seems to be some magic in `this.render` in tests and the only way to hook into the same magic myself has been to define the template as `layout` in a component. Is there a way to manually render these templates?

**Comment by rwwagner90** [comment]
This has proved to be impossible to get working. Since I have not been able to figure out a solution, or encountered anyone who has, I will assume it is impossible for now. Please feel free to resurrect the issue, if it is possible.

**Comment by Talento90** [comment]
How did you solve this problem? I am having the same question!

**Comment by GavinJoyce** [comment]
@rwwagner90 @Talento90 this might solve it for you:

<img width="803" alt="screen shot 2018-01-25 at 19 51 49" src="https://user-images.githubusercontent.com/2526/35409133-385a0136-0209-11e8-93eb-882354c391cd.png">

**Comment by rwwagner90** [comment]
Thanks for the suggestion! I can't even remember what I was trying to use this for now though 😂
