### ISSUE TITLE
SyntaxError with Addon Using `included` Hook

### ISSUE THREAD

**Issue by DHedgecock** [ember-cli/ember-cli-htmlbars-inline-precompile#66]
Hello,

My team is using your package in the component files of an addon like so:

`/addon/components/some-component/component.js`

```javascript
import Ember from 'ember';
import hbs from 'htmlbars-inline-precompile';

export default Ember.Component.extend({
  layout: hbs`IMPORTANT STUFF {{yield}}`
});
```

This works great until I attempt to add an `included` hook to the addon `index.js` file:

```javascript
/* jshint node: true */
'use strict';

module.exports = {
  name: 'neat-addon',

  included(app) {
    this._super.included(app);
  }
};
```

As soon as I add that included hook I get this error attempting to run the addon or use it inside of an Ember app:

```
File: inline-precompile/components/test-component/component.js
The Broccoli Plugin: [Babel] failed with:
SyntaxError: inline-precompile/components/test-component/component.js: Line 9: hbs should be invoked with a single argument: the template string

export default Ember.Component.extend({
  layout: hbs(_templateObject)
});
```

Running:

```
ember-cli: 2.9.1
node: 6.9.1
os: darwin x64
```

with:

```
"dependencies": {
  "ember-cli-babel": "^5.1.10",
  "ember-cli-htmlbars": "^1.0.10",
  "ember-cli-htmlbars-inline-precompile": "^0.3.6"
},
```

Any ideas why using the included hook in the addon would cause this error?

Thanks for the awesome tool!

**Comment by rwjblue** [comment]
You are not invoking super quite right, though I'm not certain if that is the fundamental issue. 

It should be:

    this._super.included.apply(this, arguments);

**Comment by DHedgecock** [comment]
YASSSSSS. Thank you @rwjblue !!!

So is this always the correct way to invoke super for this hook? In the ember-cli guide at [Developing Addons and Blueprints](https://ember-cli.com/extending/#developing-addons-and-blueprints)  there are examples with:

- no `_super`
- `this._super.included(app);`
-`return this._super.included(app);` (for an in-repo addon)

I'd be happy to submit a PR updating the docs for ember-cli if this is always the correct syntax: `this._super.included.apply(this, arguments);`

Thanks again for the SUPER fast response.

**Comment by rwjblue** [comment]
Yes, those examples are wrong. I'd love a PR fixing.

**Comment by rwjblue** [comment]
Closing since this seems resolved now
