### ISSUE TITLE
Registry Integration

### ISSUE THREAD

**Issue by rwjblue** [ember-cli/ember-cli-htmlbars-inline-precompile#7]
I am opening an issue here to dump some thoughts on how to take this addon a bit further, and how things like this can work in the future.

Random musings / brain dump:
- [registration should use the registry](https://github.com/pangratz/ember-cli-htmlbars-inline-precompile/blob/master/index.js#L13-L21) and [ember-cli-babel](https://github.com/babel/ember-cli-babel/blob/master/index.js#L32) should be getting the available plugins out of the registry.
  
  This prevents users from having to manually edit the `Brocfile.js` as described in the README here, and also allows super easy infrastructure for future babel plugins in the Ember CLI world.
  
  ember-cli-htmlbars does this exact thing to allow addons to add HTMLBars AST plugins ([see here](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/ember-addon-main.js#L63-L87)).
- Use ember-cli-htmlbars's to do the precompilation (or at least provide the options to `compile` so that AST plugins are available to precompilation).
- Add to ember-cli apps/addons by default as a devDep.  Once the above items are resolved, I would like to add this to ember-cli's default out of the box setup.

@pangratz - Does this all make sense?  Can you help spearhead these changes?

**Comment by stefanpenner** [comment]
> registration should use the registry and ember-cli-babel should be getting the available plugins out of the registry.

this may also enable this to work correctly in nested-addons

**Comment by rwjblue** [comment]
> this may also enable this to work correctly in nested-addons

Exactly!

**Comment by stefanpenner** [comment]
I think when we nail ^^, we should include this by default in ember-cli.

**Comment by pangratz** [comment]
Thank you so much for the directions @rwjblue :heart_eyes:. Your outline of using a registry for the plugins is definitely the way to go. I'll open a PR on `ember-cli-babel` shortly so we can see if I understood everything correctly.

> Use ember-cli-htmlbars's to do the precompilation (or at least provide the options to compile so that AST plugins are available to precompilation).

I think I am gonna need help with that since I am not sure how to exactly reuse the precompilation functionality from `ember-cli-htmlbars` within `ember-cli-htmlbars-inline-precompile`...

**Comment by rwjblue** [comment]
> I think I am gonna need help with that since I am not sure how to exactly reuse the precompilation functionality from ember-cli-htmlbars within ember-cli-htmlbars-inline-precompile

I think we just need to expose a mechanism to the registered plugin, to preprocess a given string (without broccoli tree).  So adding a `compileString` to [this object that is registered](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/ember-addon-main.js#L26-L33) *should* do the trick.  Then ember-cli-htmlbars-inline-precompile could grab the ember-cli-htmlbars's wrapper object out of the registry and call `plugin.compileString('whatever string I have here');`.

**Comment by pangratz** [comment]
Ah, right. Thanks, will do that.

**Comment by rwjblue** [comment]
ember-cli-htmlbars@0.7.7 has the tweaks suggested above, should be ready for testing here...

**Comment by pangratz** [comment]
> ember-cli-htmlbars@0.7.7 has the tweaks suggested above, should be ready for testing here...

:heart_eyes: 

I opened a PR which refactors the `htmlbars-inline-precompile` setup according to this issue #9. Once ember-cli/ember-cli-htmlbars#53 is merged and a new version of `ember-cli-babel` is released, I will update ...
