### ISSUE TITLE
Could not find module `htmlbars-inline-precompile` imported from ...

### ISSUE THREAD

**Issue by tniezurawski** [ember-cli/ember-cli-htmlbars-inline-precompile#71]
... <- here goes integration test "name-path" for component

In my component's integration test I make import:
```javascript
import hbs from 'htmlbars-inline-precompile';
```
and use `hbs` this way:
```javascript
this.render(hbs`
  {{component/component-name}}
`);
```

This works good in version: `0.3.6` but I experience the error mentioned in the title in version `0.4.0`.
I'm running on `ember-cli: 2.12.2` if that matters.

Did I miss something in the latest upgrade?

**Comment by rwjblue** [comment]
0.4.0 requires a miner-cli-babel@6, did you also update that? 

We need to make this a peerDependency so you would see a warning about this when installing...

**Comment by tniezurawski** [comment]
I didn't ;)

So now I upgrade these two together and everything is working properly :tada:
```
ember-cli-babel                        5.2.4  →         6.0.0
ember-cli-htmlbars-inline-precompile   0.3.6  →         0.4.0
```

Thanks!

**Comment by rwjblue** [comment]
No problem! We definitely need to make this a bit more obvious.  I think the first step is `peerDependnecies`, but we should probably also check `this.parent.addons` and see what ember-cli-babel version is in use then warn as appropriate...

**Comment by dfalling** [comment]
I'm having this same problem, even after updating both of the packages:
```
    "ember-cli-babel": "6.1.0",
    "ember-cli-htmlbars-inline-precompile": "0.4.2",
```

What else do I need to do?  All of my packages are up to date.

**Comment by rwjblue** [comment]
@dfalling - I've also seen this reported by @lukemelia in slack, is there a way that you might be able to create a demo for me to look at?

**Comment by dfalling** [comment]
@rwjblue - Sure, I'll try to whip together a much smaller demo that illustrates my problems.  Thanks!

**Comment by dfalling** [comment]
https://github.com/dfalling/hbs_demo

I ended up slimming down an existing app rather than trying to build up a new one with the same problems.  If there's too much noise from the addons I've, I can do a few more passes through to clean them up.

**Comment by lukemelia** [comment]
Thanks for putting this together @dfalling! In case, it help narrow things down, we use `ember-cli-sass` and the `active-model-adapter` but not `ember-cli-mocha`, `ember-cli-chai`, or `ember-cli-stylelint`.

**Comment by rwjblue** [comment]
OK, I've tracked down what is going on. Trying to work on a fix.

**Comment by dfalling** [comment]
Awesome, thanks for the update.  If there's anything I can do to help, I'm happy to throw some time at it as well.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli/pull/7036 fixes on the ember-cli side, but there are changes that should be made to the various linters too.

**Comment by rwjblue** [comment]
The following PR's should fix the issue for most folks that are hitting this:

* https://github.com/sir-dunxalot/ember-cli-sass-lint/pull/11
* https://github.com/billybonks/ember-cli-stylelint/pull/66 
* https://github.com/tomasbasham/ember-cli-scss-lint/pull/12

Side note: why are there so many different style linters?

**Comment by NLincoln** [comment]
We are running into this inside of our app. 

We do not use any style linters, but do use `ember-cli-sass`. All are upgraded to the latest versions.
