### ISSUE TITLE
TypeError: Cannot read property 'apply' of undefined...

### ISSUE THREAD

**Issue by batosi175** [ember-cli/ember-cli-htmlbars-inline-precompile#75]
tried installing an older version of ember for a project i need to work on and i'm starting to get this error as of today. 

TypeError: Cannot read property 'apply' of undefined
    at Class.init (/Users/Carlos/Documents/Ember/node_modules/ember-cli-htmlbars-inline-precompile/index.js:15:21)
    at new Class (/Users/Carlos/Documents/Ember/node_modules/core-object/core-object.js:18:12)
    at /Users/Carlos/Documents/Ember/node_modules/ember-cli/lib/models/addons-factory.js:48:19
    at visit (/Users/Carlos/Documents/Ember/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
    at DAG.topsort (/Users/Carlos/Documents/Ember/node_modules/ember-cli/lib/utilities/DAG.js:82:7)
    at AddonsFactory.initializeAddons (/Users/Carlos/Documents/Ember/node_modules/ember-cli/lib/models/addons-factory.js:44:9)
    at Project.initializeAddons (/Users/Carlos/Documents/Ember/node_modules/ember-cli/lib/models/project.js:375:36)
    at Project.eachAddonCommand (/Users/Carlos/Documents/Ember/node_modules/ember-cli/lib/models/project.js:426:10)
    at module.exports (/Users/Carlos/Documents/Ember/node_modules/ember-cli/lib/cli/lookup-command.js:34:13)
    at CLI.<anonymous> (/Users/Carlos/Documents/Ember/node_modules/ember-cli/lib/cli/cli.js:36:26)

package.json:

"devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "ember-cli": "1.13.14",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-bootstrap-datepicker": "0.5.4",
    "ember-cli-bootstrap-sassy": "^0.0.18",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.1.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-moment": "^0.0.2",
    "ember-cli-qunit": "^1.0.4",
    "ember-cli-release": "0.2.8",
    "ember-cli-sass": "^4.0.1",
    "ember-cli-sri": "^1.2.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-d3": "^0.1.0",
    "ember-data": "1.13.15",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-export-application-global": "^1.0.4",
    "ember-metrics": "0.8.1",
    "ember-modal-dialog": "0.8.5",
    "moment": "2.10.3"
  }

bower.json: 
{
  "name": "",
  "dependencies": {
    "ember": "1.13.12",
    "ember-cli-shims": "0.0.6",
    "ember-cli-test-loader": "0.2.1",
    "ember-data": "1.13.15",
    "ember-load-initializers": "0.1.7",
    "ember-qunit": "0.4.16",
    "ember-qunit-notifications": "0.1.0",
    "ember-resolver": "~0.1.20",
    "jquery": "1.11.3",
    "loader.js": "ember-cli/loader.js#3.4.0",
    "qunit": "~1.20.0",
    "bootstrap-sass": "~3.3.5",
    "d3": "~3.5.6",
    "bootstrap-datepicker": "~1.4.0",
    "jquery.inputmask": "^3.3.1"
  }
}

not sure if it is because i'm on an older version of ember of due to the update that happened to the 3.x version of this package.

**Comment by batosi175** [comment]
Changed my ember-cli-htmlbars-inline-precompile from "^0.3.1" to "^0.3.1 <0.3.6".  and it now builds again. was there a dependency introduced in the 0.3.8 version?

**Comment by rwjblue** [comment]
No dependencies changed, but very old ember-cli versions didn't properly support `init` calling `_super`.  You should absolutely look into updating your ember-cli version, there has been a massive amount of improvements made...

**Comment by steveax** [comment]
FYI, we're on ember* v2.4.x (which is still supported as an LTS, no?) and this broke us.

**Comment by rwjblue** [comment]
ember-cli does not have any LTS system, only Ember itself does. 

I'm happy to fix this, just haven't had a chance yet 😔

**Comment by steveax** [comment]
@rwjblue, thanks and understood, meant that as a heads up that this might break less than "very old" installs.

**Comment by MiguelMadero** [comment]
I left a comment with some info. 

https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/commit/62cd383bdc10b068b4b96cee395bd571a9b14239#commitcomment-21993131
