### ISSUE TITLE
2.13 Addon Dependency Usage

### ISSUE THREAD

**Issue by DHedgecock** [ember-cli/ember-cli-htmlbars-inline-precompile#79]
Hello, I know that this isn't a currently 'supported' use case, but our team has a few addons that use this package to declare the template files for components inside the component file instead of the template file. It's really, really nice for making small components easy to work with when all of the assets are in one file instead of two.

After updating the addons to CLI 2.13, we can no longer use the addons in consuming Apps that are version less than 2.13. This package expects Babel6 to be in use, and the application build errors when trying to consume the 2.13+ addon that has this package as a dependency (rather than dev-depdency).

Is there a way that we can resolve this (other than moving all the templates into .hbs files)? Would be happy to help if hands are needed!

Here is an example of the type of component files we have in the addons:

```
import Component from 'ember-component';
import hbs from 'htmlbars-inline-precompile';

export default Component.extend({
  state: false,
  tagName: '',

  actions: {
    close() {
      this.send('setFalse');
    },
    open() {
      this.send('setTrue');
    },
    setFalse() {
      this.set('state', false);
    },
    setTrue() {
      this.set('state', true);
    },
    toggleState() {
      this.toggleProperty('state');
    }
  },

  // Layout
  // ---------------------------------------------------------------------------
  layout: hbs`
    {{yield
      state
      (hash
        setTrue=(action 'setTrue')
        setFalse=(action 'setFalse')
        open=(action 'open')
        close=(action 'close')
        toggleState=(action 'toggleState')
      )
    }}
  `
``` 

Thanks!

**Comment by rwjblue** [comment]
FWIW, I am working on this now.  The basic issue comes down to https://github.com/ember-cli/ember-cli-version-checker/issues/27.

**Comment by DHedgecock** [comment]
![Yasss](https://media.giphy.com/media/kGZ4jJguXT5C0/giphy.gif)

That's awesome 👍

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli-version-checker/pull/41 should unblock the main issue, needs review before landing and releasing as v2.0.0.

**Comment by rwjblue** [comment]
https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/pull/80 should fix things for ember-cli-htmlbars-inline-precompile@0.3, but would love some testers...

**Comment by DHedgecock** [comment]
I'm in, what should I update to test?

**Comment by rwjblue** [comment]
I think you should basically just need to update your nested deps that needed 0.3.x to use v0.3.10 (which I just published).

**Comment by DHedgecock** [comment]
Works with 0.3.11 👍 

Thanks for the uber-fast turnaround.
