### ISSUE TITLE
hbs is not defined

### ISSUE THREAD

**Issue by mixonic** [ember-cli/ember-cli-htmlbars-inline-precompile#8]
I'm upgrading a project to a new version of Ember-CLI and getting an "hbs is not defined" ReferenceError. The transpiled template:

![](https://api.monosnap.com/rpc/file/download?id=IgIgg34v01MNjUjvMn6Hm4Rwa1gMmj)

From a test like so

``` js
import {
  moduleForComponent,
  test
} from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';
import Ember from 'ember';

var template = hbs`{{service-scaler containerCount=count}}`

moduleForComponent('service-scaler', 'ServiceScalerComponent', {
  integration: true
});

test('it renders', function() {
  expect(2);

  this.set('count', 1);
  this.render(template);
  assert.ok(this.$('input').length, 'input is present');
});
```

```
> ember -v
version: 0.2.5
node: 0.12.2
npm: 2.10.0
```

v0.1.0 of the precompiler.

**Comment by mixonic** [comment]
Seems `TaggedTemplateExpression` is not being called in the plugin.

**Comment by mixonic** [comment]
Ergh. Recreated with Babel 5.2.17, 5.3.3, 5.4.4

**Comment by pangratz** [comment]
Thanks for reporting this! I will try to tackle this once #7 is addressed. Since babel is moving so fast I try to add some kind of smoke test for the future to check if the latest babel version works.

**Comment by mixonic** [comment]
Hm, like an ember-try for babel :-) I'm not sure it is a babel issue at all though. I can likely repro with a branch of https://github.com/aptible/dashboard.aptible.com

**Comment by pangratz** [comment]
Something like that, yeah :wink: A reproduction-repo would be wunderbar.

**Comment by pangratz** [comment]
I think I might have good news for you:

```
cd /tmp
hub clone pangratz/ember-cli-htmlbars-inline-precompile
cd ember-cli-htmlbars-inline-precompile
hub checkout https://github.com/pangratz/ember-cli-htmlbars-inline-precompile/pull/9
npm install
npm link

cd ..

hub clone babel/ember-cli-babel
cd ember-cli-babel
hub checkout https://github.com/babel/ember-cli-babel/pull/42
npm install
npm link

cd ..
git clone https://github.com/aptible/dashboard.aptible.com
cd dashboard.aptible.com
npm link ember-cli-babel
npm link ember-cli-htmlbars-inline-precompile
npm install ember-cli-htmlbars@0.7.7 --save-dev
npm install
```

Creating a test using the `hbs` precompile stuff works. So it looks like #9 solves this. I will open a PR on https://github.com/aptible/dashboard.aptible.com updating the dependencies (`ember-cli-qunit`, `ember-cli-htmlbars`, `ember-cli-htmlbars-inline-precompile` and ` ember-cli-babel`) once all versions are released. :dancer:

**Comment by mixonic** [comment]
@pangratz amaze. Thank you so much for taking the time to repro before I got you anything. I really appreciate your great work on this addon :-)

**Comment by Kuzirashi** [comment]
Does it work in acceptance tests? I've imported it, but hbs is still undefined.

**Comment by pangratz** [comment]
Can you give a sample code? Which version are you using?

**Comment by locks** [comment]
Hello everyone, can we get a reproduction that shows this is still an issue?

**Comment by rwjblue** [comment]
I believe this is resolved (and this issue is pretty stale).  Closing this, but if there are still folks with issues please open a new issue with a reproduction.
