### ISSUE TITLE
With 1.0.0 "broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: `() => __dirname`."

### ISSUE THREAD

**Issue by johnunclesam** [ember-cli/ember-cli-htmlbars-inline-precompile#89]
From `0.4.4` to `1.0.0` and I receive this:

```
$ ember s
Livereload server on http://localhost:49153
broccoli-babel-transpiler is opting out of caching due to a plugin that does not provide a caching strategy: `() => __dirname`.
```

**two times.**

I'm using:

```
"ember-cli-babel": "^6.6.0",
"ember-cli-babili": "~0.1.4",
```

**Comment by rwjblue** [comment]
This also requires a bump of broccoli-babel-transpiler, can you do a `yarn upgrade broccoli-babel-transpiler` to get the latest and let us know if that resolves the issue?

**Comment by smottt** [comment]
Solved the issue for me, thanks!

**Comment by rwjblue** [comment]
Awesome, thank you for confirming!

We need to update our peerDependency minimum for this I guess....

**Comment by johnunclesam** [comment]
Fixed thanks.
